const projects = [
  {
    id: "5",
    title: "Runneth Over",
    description:
      "A global fashion marketplace platform that connects users to thousands of brands worldwide. Using AI-powered image search that support real-time price tracking, Runneth Over helps users discover, track, and shop their favorite styles effortlessly. From everyday essentials to luxury finds, it acts as your personal fashion assistant.",
    features: [
      "AI-powered visual search using Google Vision",
      "Image upload for product matching",
      "Real-time price tracking across retailers",
      "Affiliate marketplace integration",
      "User authentication and profile management",
      "Product favorites and wishlists",
      "Admin analytics dashboard",
      "Multi-brand product discovery",
      "Price comparison and deal alerts",
    ],
    image: "/projects/runneth/runneth1.png",
    images: [
      "/projects/runneth/runneth1.png",
      "/projects/runneth/runneth2.png",
      "/projects/runneth/runneth3.png",
      "/projects/runneth/runneth4.png",
    ],
    technologies: [
      "React",
      "Express.js",
      "Node.js",
      "Google Vision API",
      "MongoDB",
      "Affiliate APIs",
      "JWT Authentication",
    ],
    liveUrl: "https://runnethover.io",
    category: "client",
    featured: true,
    createdAt: "2025-10-22",
  },
  {
    id: "8",
    title: "Dynamic Form Creator",
    description:
      "A comprehensive full-stack web application that enables users to create, customize, and manage dynamic forms with real-time responses. Built with Next.js 14 and featuring a modern tech stack, this platform provides seamless form building experience with drag-and-drop functionality, user authentication, and robust data management capabilities.",
    features: [
      "Dynamic form builder with drag-and-drop interface",
      "User authentication and authorization with NextAuth.js",
      "Real-time form response collection and management",
      "MongoDB integration for persistent data storage",
      "Responsive design with Tailwind CSS and ShadCN UI components",
      "Custom form field types (text, email, select, checkbox, radio, textarea)",
      "Form sharing via unique slugs and public URLs",
      "User dashboard for form management and analytics",
      "Form response export and data visualization",
      "Email restrictions and form access controls",
      "Form submission timestamps and IP tracking",
      "Secure password hashing with bcryptjs",
      "TypeScript for enhanced code reliability",
      "Server-side rendering and API routes with Next.js App Router",
      "Cloudinary integration for file uploads (optional)",
      "Deployment-ready with Vercel optimization",
    ],
    image: "/projects/form-creator/project1.png",
    images: [
      "/projects/form-creator/project1.png",
      "/projects/form-creator/project2.png",
      "/projects/form-creator/project3.png",
      "/projects/form-creator/project4.png",
    ],
    technologies: [
      "Next.js 14",
      "TypeScript",
      "React",
      "NextAuth.js",
      "MongoDB",
      "Mongoose",
      "Tailwind CSS",
      "ShadCN UI",
      "bcryptjs",
      "Node.js",
      "Vercel",
      "Cloudinary",
      "JWT",
      "REST API",
      "Server-Side Rendering",
    ],
    liveUrl: "https://advance-forms.vercel.app/",
    githubUrl: "https://github.com/Hayzedd-A/form-creator",
    category: "personal",
    featured: true,
    createdAt: "2025-08-08",
  },
  {
    id: "3",
    title: "A Portfolio",
    description:
      "A portfolio website for a developer to showcase skill, experience, and get to know me better. Features include, light and dark mode, four color scheme, admin section using Next.js authentication, visitor analytics.",
    features: [
      "Light/Dark mode support",
      "Multiple color schemes",
      "Admin dashboard with auth",
      "Visitor analytics tracking",
      "Animated transitions (GSAP, Framer Motion)",
      "Github stats API",
      "Sending email form",
    ],
    image: "/projects/portfolio/portfolio1.png",
    images: [
      "/projects/portfolio/portfolio1.png",
      "/projects/portfolio/portfolio2.png",
      "/projects/portfolio/portfolio3.png",
      "/projects/portfolio/portfolio4.png",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "MongoDB",
      "framer-motion",
      "GSAP",
      "nodemailer",
      "maxmind/geoip",
    ],
    githubUrl: "https://github.com/Hayzedd-A/hayzedd-the-developer",
    liveUrl: "https://hayzedd-the-developer.vercel.app/contact",
    category: "personal",
    featured: false,
    createdAt: "2025-01-10",
  },
  {
    id: "8",
    title: "Moodbrary",
    description:
      "An AI-powered artifact search platform that helps users discover design products across multiple websites. Users input project details and upload inspiration images, and the system uses AI to analyze requirements and return matching artifacts from various vendors.",
    features: [
      "AI-powered product search and matching",
      "Image upload and analysis",
      "Multi-criteria search (project type, budget, keywords)",
      "User authentication and favorites",
      "Admin dashboard for product management",
      "Email notifications",
      "Cloud-based image storage",
      "Real-time search results",
    ],
    image: "/projects/moodbrary/moodbrary1.png",
    images: [
      "/projects/moodbrary/moodbrary1.png",
      "/projects/moodbrary/moodbrary2.png",
      "/projects/moodbrary/moodbrary3.png",
      "/projects/moodbrary/moodbrary4.png",
    ],
    technologies: [
      "Next.js",
      "JavaScript",
      "MongoDB",
      "Cloudinary",
      "OpenAI API",
      "NextAuth.js",
      "Nodemailer",
      "Tailwind CSS",
    ],
    // githubUrl: "https://github.com/yourusername/moodbrary",
    liveUrl: "https://gofed.vercel.app/",
    category: "client",
    featured: true,
    createdAt: "2025-10-12",
  },
  {
    id: "9",
    title: "StoreTrack – Inventory & POS System",
    description:
      "A streamlined inventory management and Point of Sale (POS) system designed for small business owners. StoreTrack enables efficient product management, real-time sales tracking, and accurate profit calculation at the point of sale. Built with a modern full-stack architecture, the application focuses on speed, simplicity, and reliability, providing essential retail tools without the complexity of multi-user systems.",
    features: [
      "Single-user (sole proprietorship) system optimized for small business owners",
      "Comprehensive product management with category, barcode, shelf number, and media support",
      "Custom unit configuration for restock and sales (flexible inventory control)",
      "Low stock threshold alerts for proactive inventory management",
      "Real-time POS system with product search by name and SKU",
      "Barcode scanning integration for instant cart addition",
      "Accurate profit calculation at the point of sale to prevent pricing inconsistencies",
      "Sales summary with automatic receipt generation",
      "Printable PDF receipts for transaction records",
      "Dashboard with sales and profit insights (numeric and graphical)",
      "Cloudinary integration for product image uploads and optimization",
      "Responsive and fast UI for seamless in-store usage",
      "Data persistence with MongoDB and efficient querying",
      "Type-safe development using TypeScript",
      "Optimized for performance and scalability using modern React patterns",
    ],
    image: "/projects/store-track/project1.png",
    images: [
      "/projects/store-track/project1.png",
      "/projects/store-track/project2.png",
      "/projects/store-track/project3.png",
      "/projects/store-track/project4.png",
      "/projects/store-track/project5.png",
    ],
    technologies: [
      "Next.js 16",
      "TypeScript",
      "React",
      "MongoDB",
      "Mongoose",
      "Tailwind CSS",
      "Material UI (MUI)",
      "React Query",
      "Zod",
      "React Hook Form",
      "Cloudinary",
      "ZXing",
      "Quagga2",
      "Recharts",
      "Node.js",
      "REST API",
    ],
    liveUrl: "https://store-track-eta.vercel.app",
    githubUrl: "https://github.com/Hayzedd-A/store-track",
    category: "personal",
    featured: true,
    createdAt: "2026-02-15",
  },
  {
    id: "10",
    title: "Digital Catalog & Price List Web App",
    description:
      "A digital catalog and price list web application built for small businesses to showcase products without requiring user authentication. The platform provides a seamless browsing experience with category-based navigation, search functionality, and WhatsApp integration for direct customer engagement. It also includes a secure admin panel for managing items, tracking user interactions, and gaining insights into customer preferences.",
    features: [
      "Mobile-first, fully responsive design optimized for all devices",
      "No authentication required for customers – frictionless browsing experience",
      "Anonymous user tracking using localStorage for personalized interactions",
      "Category-based navigation with tab switching for organized browsing",
      "Global search functionality across all items and categories",
      "Favourite system with local persistence and database synchronization",
      "WhatsApp Click-to-Chat integration with pre-filled product messages",
      "Admin panel with secure login for managing catalog items",
      "CRUD operations for items including image upload and editing",
      "Cloudinary integration for efficient image storage and optimization",
      "Favourites analytics dashboard to track most popular items",
      "RESTful API architecture with structured endpoints",
      "Optimized data fetching and rendering using modern Next.js patterns",
      "Scalable MongoDB schema design with Mongoose",
      "Environment-based configuration for flexible deployments",
    ],
    image: "/projects/digital-catalog/project1.png",
    images: [
      "/projects/digital-catalog/project1.png",
      "/projects/digital-catalog/project2.png",
      "/projects/digital-catalog/project3.png",
      "/projects/digital-catalog/project4.png",
    ],
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "MongoDB",
      "Mongoose",
      "Tailwind CSS",
      "Cloudinary",
      "Lucide React",
      "Node.js",
      "REST API",
      "LocalStorage",
    ],
    liveUrl: "https://joms-craft.vercel.app/",
    githubUrl: "https://github.com/Hayzedd-A/joms-craft",
    category: "personal",
    featured: true,
    createdAt: "2026-01-10",
  },
  {
    id: "4",
    title: "Errand Buddies",
    description:
      "An E-Commerce website where vendor can onboard, upload products and make sales on their product. Customers can also onboard, make purchase on products and track their order",
    features: [
      "Vendor onboarding & product upload",
      "Customer registration and purchases",
      "Order tracking system",
      "Payment integration (Paystack)",
      "Chating with Socket.IO",
      "Identity verification with YouVerify",
      "SMS sending with termii",
      "Image upload and optimization with cloudinary",
    ],
    image: "/projects/errandBuddies/project1.png",
    images: [
      "/projects/errandBuddies/project1.png",
      "/projects/errandBuddies/project2.png",
      "/projects/errandBuddies/project3.png",
      "/projects/errandBuddies/project4.png",
    ],
    technologies: [
      "Express.js",
      "Socket IO",
      "React",
      "YouVerify ID",
      "Cloudinary",
      "Paystack",
      "SMS",
    ],
    liveUrl: "https://errandbuddies.net",
    category: "client",
    featured: true,
    createdAt: "2024-11-10",
  },
  {
    id: "2",
    title: "Phone Repair web App",
    description:
      "A website for a phone engineer to show their skill and place product for sale",
    features: [
      "Engineer portfolio showcase",
      "Product listing for sale",
      "Authentication with NextAuth",
      "Responsive UI with Tailwind",
      "MongoDB product management",
      "Admin section for managing products, blogs, services",
    ],
    image: "/projects/phone-management/phoneManagement1.png",
    images: [
      "/projects/phone-management/phoneManagement1.png",
      "/projects/phone-management/phoneManagement2.png",
      "/projects/phone-management/phoneManagement3.png",
      "/projects/phone-management/phoneManagement4.png",
      "/projects/phone-management/phoneManagement5.png",
    ],
    technologies: ["Next.js", "TypeScript", "Next-auth", "Mongodb", "Tailwind"],
    githubUrl: "https://github.com/Hayzedd-A/tech-engineering",
    liveUrl: "https://tech-engineering-hazel.vercel.app/",
    category: "personal",
    featured: true,
    createdAt: "2025-04-20",
  },
];
